target_sources(VoxelGame PRIVATE
    ./include/WorldGeneration/TerrainGenerator.hpp
    ./include/WorldGeneration/Biome.hpp
    ./include/WorldGeneration/StructureGenerator.hpp
    ./include/WorldGeneration/TreeNoise.hpp
    ./include/WorldGeneration/CaveGenerator.hpp
    ./include/WorldGeneration/noiseutils.hpp
    ./include/WorldGeneration/GenerationData.hpp
    ./include/WorldGeneration/WorldGenerator.hpp
    ./include/WorldGeneration/TerrainHeightGenerator.hpp
    ./include/Logger.hpp
    ./include/MainMenuLayer.hpp
    ./include/GameData/BlockIds.hpp
    ./include/GameData/BlockTemplate.hpp
    ./include/GameData/OreData.hpp
    ./include/GameData/Block.hpp
    ./include/GameData/Structure.hpp
    ./include/GameData/ChunkSection.hpp
    ./include/GameData/BlockGeometry.hpp
    ./include/GameData/BlockStates/BlockStateContainer.hpp
    ./include/GameData/BlockStates/BlockState.hpp
    ./include/GameData/BlockStates/WaterBlockState.hpp
    ./include/GameData/GameData.hpp
    ./include/GameData/BiomeIds.hpp
    ./include/World.hpp
    ./include/Gui/DebugLayout.hpp
    ./include/Gui/Rectangle.hpp
    ./include/Gui/Widget.hpp
    ./include/Gui/Text.hpp
    ./include/Gui/Layout.hpp
    ./include/Gui/HotbarLayout.hpp
    ./include/Gui/GUI.hpp
    ./include/Gui/ItemLayout.hpp
    ./include/Gui/Image.hpp
    ./include/Gui/UiMargin.hpp
    ./include/Gui/IngameLayerGUI.hpp
    ./include/Gui/MainMenuLayout.hpp
    ./include/Gui/ItemWidget.hpp
    ./include/Gui/DragContext.hpp
    ./include/Gui/InventoryLayout.hpp
    ./include/Gui/UiConstraints.hpp
    ./include/Gui/UiProperties.hpp
    ./include/Utility.hpp
    ./include/GameLayer.hpp
    ./include/Collision.hpp
    ./include/Rendering/Item.hpp
    ./include/Rendering/RenderQuad.hpp
    ./include/Rendering/WaterRenderBuffers.hpp
    ./include/Rendering/GBuffer.hpp
    ./include/Rendering/Light.hpp
    ./include/Rendering/Window.hpp
    ./include/Rendering/Vertex.hpp
    ./include/Math/Cuboid.hpp
    ./include/Math/Face.hpp
    ./include/Math/Plane.hpp
    ./include/Math/Ray.hpp
    ./include/IngameLayer.hpp
    ./include/Events/EventDispatcher.hpp
    ./include/Events/CallbackHandle.hpp
    ./include/Events/CallbackList.hpp
    ./include/Events/Event.hpp
    ./include/Application.hpp
    ./include/Components/ItemComponent.hpp
    ./include/Components/MultiMeshRenderComponent.hpp
    ./include/Components/PlayerComponent.hpp
    ./include/Components/LightComponent.hpp
    ./include/Components/InventoryComponent.hpp
    ./include/Components/MeshRenderComponent.hpp
    ./include/Components/RigidBodyComponent.hpp
    ./include/Components/VelocityComponent.hpp
    ./include/Components/ChunkComponent.hpp
    ./include/Components/CameraComponent.hpp
    ./include/Components/BlockSelectionComponent.hpp
    ./include/Components/TransformationComponent.hpp
    ./include/Components/CollisionComponent.hpp
    ./include/Components/SkyboxComponent.hpp
    ./include/Color.hpp
    ./include/Systems/ItemSystem.hpp
    ./include/Systems/InputSystem.hpp
    ./include/Systems/SkyboxSystem.hpp
    ./include/Systems/CollisionSystem.hpp
    ./include/Systems/ChunkUpdateSystem.hpp
    ./include/Systems/PhysicsSystem.hpp
    ./include/Systems/ChunkCreateSystem.hpp
    ./include/Systems/DayNightSystem.hpp
    ./include/Systems/DebugRenderSystem.hpp
    ./include/Systems/MeshRenderSystem.hpp
    ./include/Systems/CloudSystem.hpp
    ./include/Systems/PlayerMovementSystem.hpp
    ./include/Systems/System.hpp
    ./include/Systems/CameraSystem.hpp
    ./include/Typedefs.hpp
    ./include/Configuration.hpp
    ./include/Resources/Geometry.hpp
    ./include/Resources/Resource.hpp
    ./include/Resources/TextureAtlas.hpp
    ./include/Resources/ResourceManager.hpp
    ./include/Resources/Texture.hpp
    ./include/Resources/ResourceIDs.hpp
    ./include/Resources/Font.hpp
    ./include/Resources/Material.hpp
    ./include/Resources/Shader.hpp
    ./src/WorldGeneration/StructureGenerator.cpp
    ./src/WorldGeneration/WorldGenerator.cpp
    ./src/WorldGeneration/noiseutils.cpp
    ./src/WorldGeneration/Biome.cpp
    ./src/WorldGeneration/TerrainGenerator.cpp
    ./src/WorldGeneration/CaveGenerator.cpp
    ./src/WorldGeneration/TreeNoise.cpp
    ./src/WorldGeneration/TerrainHeightGenerator.cpp
    ./src/Collision.cpp
    ./src/Configuration.cpp
    ./src/IngameLayer.cpp
    ./src/Color.cpp
    ./src/Application.cpp
    ./src/GameData/BlockGeometry.cpp
    ./src/GameData/GameData.cpp
    ./src/GameData/ChunkSection.cpp
    ./src/GameData/BlockStates/BlockStateContainer.cpp
    ./src/GameData/Block.cpp
    ./src/MainMenuLayer.cpp
    ./src/GameLayer.cpp
    ./src/Utility.cpp
    ./src/Gui/HotbarLayout.cpp
    ./src/Gui/Rectangle.cpp
    ./src/Gui/Image.cpp
    ./src/Gui/UiMargin.cpp
    ./src/Gui/Widget.cpp
    ./src/Gui/IngameLayerGUI.cpp
    ./src/Gui/UiConstraints.cpp
    ./src/Gui/Text.cpp
    ./src/Gui/Layout.cpp
    ./src/Gui/ItemWidget.cpp
    ./src/Gui/GUI.cpp
    ./src/Gui/ItemLayout.cpp
    ./src/Gui/DebugLayout.cpp
    ./src/Gui/InventoryLayout.cpp
    ./src/Gui/MainMenuLayout.cpp
    ./src/Logger.cpp
    ./src/Rendering/Item.cpp
    ./src/Rendering/Window.cpp
    ./src/Rendering/WaterRenderBuffers.cpp
    ./src/Rendering/GBuffer.cpp
    ./src/Rendering/RenderQuad.cpp
    ./src/Math/Ray.cpp
    ./src/Math/Face.cpp
    ./src/Math/Plane.cpp
    ./src/Math/Cuboid.cpp
    ./src/Events/EventDispatcher.cpp
    ./src/Events/Event.cpp
    ./src/World.cpp
    ./src/main.cpp
    ./src/Components/ChunkComponent.cpp
    ./src/Components/CollisionComponent.cpp
    ./src/Components/BlockSelectionComponent.cpp
    ./src/Components/CameraComponent.cpp
    ./src/Components/TransformationComponent.cpp
    ./src/Components/RigidBodyComponent.cpp
    ./src/Systems/CollisionSystem.cpp
    ./src/Systems/InputSystem.cpp
    ./src/Systems/SkyboxSystem.cpp
    ./src/Systems/MeshRenderSystem.cpp
    ./src/Systems/DebugRenderSystem.cpp
    ./src/Systems/PlayerMovementSystem.cpp
    ./src/Systems/CloudSystem.cpp
    ./src/Systems/DayNightSystem.cpp
    ./src/Systems/ChunkCreateSystem.cpp
    ./src/Systems/ChunkUpdateSystem.cpp
    ./src/Systems/PhysicsSystem.cpp
    ./src/Systems/CameraSystem.cpp
    ./src/Systems/ItemSystem.cpp
    ./src/Systems/System.cpp
    ./src/Resources/Texture.cpp
    ./src/Resources/Font.cpp
    ./src/Resources/Geometry.cpp
    ./src/Resources/Material.cpp
    ./src/Resources/TextureAtlas.cpp
    ./src/Resources/Shader.cpp
    ./src/Resources/ResourceManager.cpp
    )
