#pragma once

enum class BlockId : short {
    BLOCK_AIR, BLOCK_GRASS, BLOCK_STONE, BLOCK_BEDROCK, BLOCK_WOOD, BLOCK_STONE_BRICKS, BLOCK_STONE_FRAMED,
    BLOCK_BRICKS, BLOCK_TNT, BLOCK_STONE_CRACKED, BLOCK_STONE_COBBLE, BLOCK_SAND, BLOCK_GRAVEL,
    BLOCK_IRON, BLOCK_GOLD, BLOCK_DIAMOND, BLOCK_EMERALD, BLOCK_ORE_GOLD, BLOCK_ORE_IRON, BLOCK_ORE_COAL,
    BLOCK_BOOKSHELF, BLOCK_STONE_MOSSY, BLOCK_DIRT, BLOCK_LEAVES, BLOCK_WATER, BLOCK_LAVA,

    // the following blocks are non-solid blocks; they are made up of two orthogonal and textured 2d planes
    PLANE_GRASS,

    NUM_BLOCKS
};
