#pragma once

// give all resources an ID

using ResourceID = unsigned long;

enum RESOURCES_TEXTURES {
    TEXTURE_ATLAS,
    TEXTURE_BACKGROUND_MAIN_MENU,
    TEXTURE_WHITE,
    TEXTURE_BLACK
};

enum RESOURCES_SHADERS {
    SHADER_MESH_RENDER_TEXTURE,
    SHADER_MESH_RENDER_COLOR,
    SHADER_TEXTURE_QUAD,
    SHADER_COLOR_QUAD,
    SHADER_SKYBOX,
    SHADER_TEXT
};

enum RESOURCES_MATERIALS {
    MATERIAL_CHUNK_BLOCKS
};

enum RESOURCES_FONTS {
    FONT_KORURI
};
